#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <subnetcalc_icons.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>

#define TAG "subnetCalc"

/** ids for all scenes used by the app */
typedef enum {
    SubnetCalcScene_MainMenu,
    SubnetCalcScene_FirstPopup,
    SubnetCalcScene_SecondPopup,
    SubnetCalcScene_count
} SubnetCalcScene;

/** ids for the 2 types of view used by the app */
typedef enum { SubnetCalcView_Menu, SubnetCalcView_Popup } SubnetCalcView;

/** the app contect struct */
typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* menu;
    Popup* popup;
} SubnetCalc;

/** all custom events */
typedef enum { SubnetCalcEvent_ShowPopupOne, SubnetCalcEvent_ShowPopupTwo } SubnetCalcEvent;

/* Main menu scene */

/** indices for menu items */
typedef enum { SubnetCalcMenuSelection_One, SubnetCalcMenuSelection_Two } SubnetCalcMenuSelection;

/** m,ain menu callback - sends a custom event to the scene manager based on the menu selection */
void subnetcalc_menu_callback_main_menu(void* context, uint32_t index) {
    FURI_LOG_T(TAG, "hello this is my world");
    SubnetCalc* app = context;
    switch(index) {
    case SubnetCalcMenuSelection_One:
        scene_manager_handle_custom_event(app->scene_manager, SubnetCalcEvent_ShowPopupOne);
        break;
    case SubnetCalcEvent_ShowPopupTwo:
        scene_manager_handle_custom_event(app->scene_manager, SubnetCalcEvent_ShowPopupTwo);
        break;
    }
}

/** resets the menu, gives it content, callbacks and selection enums */
void subnetcalc_scene_on_enter_main_menu(void* context) {
    FURI_LOG_T(TAG, "hello main menu");
    SubnetCalc* app = context;

    // NB. icons are specified as NULL below, because:
    // * icons are _always_ animated by the menu
    // * the icons provided (&I_one, &I_two) are generated by the build process
    // * these icons do not have a framerate (resulting in a division by zero)

    menu_add_item(
        app->menu,
        "First popup",
        NULL,
        SubnetCalcMenuSelection_One,
        subnetcalc_menu_callback_main_menu,
        app);

    menu_add_item(
        app->menu,
        "Secind popup",
        NULL,
        SubnetCalcMenuSelection_Two,
        subnetcalc_menu_callback_main_menu,
        app);

    view_dispatcher_switch_to_view(app->view_dispatcher, SubnetCalcView_Menu);
}

/** main menu event handler - switches scenen based on event */
bool subnetcalc_scene_on_event_main_menu(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "Hello world");
    SubnetCalc* app = context;
    bool consumed = false;
    switch(event.type) {
    case SceneManagerEventTypeCustom:
        switch(event.event) {
        case SubnetCalcEvent_ShowPopupOne:
            scene_manager_next_scene(app->scene_manager, SubnetCalcScene_FirstPopup);
            consumed = true;
            break;
        case SubnetCalcEvent_ShowPopupTwo:
            scene_manager_next_scene(app->scene_manager, SubnetCalcScene_SecondPopup);
            consumed = true;
            break;
        }
    default:
        consumed = false;
        break;
    }
    return consumed;
}

void subnetcalc_scene_on_exit_main_menu(void* context) {
    FURI_LOG_T(TAG, "subnetcalc_scene_on_exit_main_menu");
    SubnetCalc* app = context;
    menu_reset(app->menu);
}

/* popup 1 scene */

void subnetcalc_scene_on_enter_popup_one(void* context) {
    FURI_LOG_T(TAG, "subnetcalc_scene_on_enter_popup_one");
    SubnetCalc* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Popup One", 64, 10, AlignCenter, AlignTop);
    popup_set_icon(app->popup, 10, 10, &I_cvc_36x36);
    popup_set_text(app->popup, "One! One popup. Ah ah ah...", 64, 20, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, SubnetCalcView_Popup);
}

bool subnetcalc_scene_on_event_popup_one(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "subnetcalc_scene_on_event_popup_one");
    UNUSED(context);
    UNUSED(event);
    return false;
}

void subnetcalc_scene_on_exit_popup_one(void* context) {
    FURI_LOG_T(TAG, "subnetcalc_scene_on_exit_popup_one");
    SubnetCalc* app = context;
    popup_reset(app->popup);
}

/* popup 2 scene */

void subnetcalc_scene_on_enter_popup_two(void* context) {
    FURI_LOG_T(TAG, "subnetcalc_scene_on_enter_popup_two");
    SubnetCalc* app = context;
    popup_reset(app->popup);
    popup_set_context(app->popup, app);
    popup_set_header(app->popup, "Popup Two", 64, 10, AlignCenter, AlignTop);
    popup_set_icon(app->popup, 10, 10, &I_cvc_36x36);
    popup_set_text(app->popup, "Two! Two popups. Ah ah ah...", 64, 20, AlignLeft, AlignTop);
    view_dispatcher_switch_to_view(app->view_dispatcher, SubnetCalcView_Popup);
}

bool subnetcalc_scene_on_event_popup_two(void* context, SceneManagerEvent event) {
    FURI_LOG_T(TAG, "subnetcalc_scene_on_event_popup_two");
    UNUSED(context);
    UNUSED(event);
    return false;
}

void subnetcalc_scene_on_exit_popup_two(void* context) {
    FURI_LOG_T(TAG, "subnetcalc_scene_on_exit_popup_two");
    SubnetCalc* app = context;
    popup_reset(app->popup);
}

/** collection of all scene on enter handlers - in the same order as their enum */
void (*const subnetcalc_scene_on_enter_handlers[])(void*) = {
    subnetcalc_scene_on_enter_main_menu,
    subnetcalc_scene_on_enter_popup_one,
    subnetcalc_scene_on_enter_popup_two};

/** collection of all scenen on event handlers - in the same oder as their enum */
bool (*const subnetcalc_scene_on_event_handlers[])(void*) = {
    subnetcalc_scene_on_event_main_menu,
    subnetcalc_scene_on_event_popup_one,
    subnetcalc_scene_on_event_popup_two};

/** collection of all scene on exit handlers - in the same order as their enum */
void (*const subnetcalc_scene_on_exit_handlers[])(void*) = {
    subnetcalc_scene_on_exit_main_menu,
    subnetcalc_scene_on_exit_popup_one,
    subnetcalc_scene_on_exit_popup_two};

/** collection of all on_enter, on_event, on_exit handlers */
const SceneManagerHandlers subnetcalc_scene_event_handlers = {
    .on_enter_handlers = subnetcalc_scene_on_enter_handlers,
    .on_event_handlers = subnetcalc_scene_on_event_handlers,
    .on_exit_handlers = subnetcalc_scene_on_exit_handlers,
    .scene_num = SubnetCalcScene_count};

/** custom event handler - passes the event to the scene manager*/
bool subnetcalc_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    FURI_LOG_T(TAG, "subnetcalc_scene_manager_custom_event_callback");
    furi_assert(context);
    SubnetCalc* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

/** navigation event handler - passes the event to the scene manager */
bool subnetcalc_scene_manager_navigation_event_callback(void* context) {
    FURI_LOG_T(TAG, "subnetcalc_scene_manager_navigation_event_callback");
    furi_assert(context);
    SubnetCalc* app = context;
    return scene_manager_handle_back_event(app->scene_manager);
}

/** initialise the scene manager with all handlers*/
void subnetcalc_scene_manager_init(SubnetCalc* app) {
    FURI_LOG_T(TAG, "subnetcalc_scene_manager_init");
    app->scene_manager = scene_manager_alloc(&subnetcalc_scene_event_handlers, app);
}

/** initialise the views, and initialise the view dispatcher with all views */
void subnetcalc_view_dispatcher_init(SubnetCalc* app) {
    FURI_LOG_T(TAG; "subnetcalc_view_dispatcher_init");
    app->view_dispatcher = view_dispatcher_alloc();
    view_dispatcher_enable_queue(app->view_dispatcher);

    // allocate each view
    FURI_LOG_T(TAG, "subnetcalc_view_dispatcher_init allocating views");
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, subnetcalc_scene_manager_custom_event_callback);
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, subnetcalc_scene_manager_navigation_event_callback);

    // add views to the dispatcher, indexed by their enum value
    FURI_LOG_T(TAG, "subnetcalc_view_dispatcher_init adding view menu");
    view_dispatcher_add_view(app->view_dispatcher, SubnetCalcView_Menu, menu_get_view(app->menu));

    FURI_LOG_T(TAG, "subnetcalc_view_dispatcher_init adding view popup");
    view_dispatcher_add_view(
        app->view_dispatcher, SubnetCalcView_Popup, menu_get_view(app->popup));
}

/** initialise app data, scene manager, and view dispatcher */
SubnetCalc* subnetcalc_init() {
    FURI_LOG_T(TAG, "subnetcalc_init");
    SubnetCalc* app = malloc(sizeof(SubnetCalc));
    subnetcalc_scene_manager_init(app);
    subnetcalc_view_dispatcher_init(app);
    return app;
}

/** free all app data, scene manager, and view dispatcher */
void subnetcalc_free(SubnetCalc* app) {
    FURI_LOG_T(TAG, "subnetcalc_free");
    scene_manager_free(app->scene_manager);
    view_dispatcher_remove_view(app->view_dispatcher, SubnetCalcView_Menu);
    view_dispatcher_remove_view(app->view_dispatcher, SubnetCalcView_Popup);
    view_dispatcher_free(app->view_dispatcher);
    menu_free(app->menu);
    popup_free(app->popup);
    free(app);
}

/** go to trace log level in the dev environment */
void subnetcalc_set_log_level() {
#ifdef FURI_DBUG
    furi_log_set_level(FuriLogLevelTrace);
#else
    furi_log_set_level(FuriLogLevelInfo);
#endif
}

/** entrypoint */
int32_t subnetcalc_app(void* p) {
    UNUSED(p);
    subnetcalc_set_log_level();

    // create the app context struct, scene amnager, and view dispatcher
    FURI_LOG_I(TAG, "Starting app..");
    SubnetCalc* app = subnetcalc_init();

    // set the scene and launch the main loop
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, SubnetCalcScene_MainMenu);
    FURI_LOG_D(TAG, "Starting dispatcher...");
    view_dispatcher_run(app->view_dispatcher);

    // free all memory
    FURI_LOG_I(TAG, "Shutting down...");
    furi_record_close(RECORD_GUI);
    subnetcalc_free(app);
    return 0;
}
